default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: solidus_example_development

test:
  <<: *default
  database: solidus_example_test

production:
  <<: *default
  database: solidus_example_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
